# docker-compose.yml
version: '3.8'

services:
  mobile-app:
    build: ./mobile-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
      - ai-service

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/urbanjungle
      - PG_CONN_STRING=postgres://postgres:password@postgres:5432/urbanjungle
    depends_on:
      - mongo
      - postgres

  ai-service:
    build: ./ai-service
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service/models:/app/models
      - ./ai-service/data:/app/data

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=urbanjungle
    volumes:
      - postgres_data:/var/lib/postgresql/data

  game-server:
    build: ./game-engine
    ports:
      - "8080:8080"

volumes:
  mongodb_data:
  postgres_data: